### ISSUE TITLE
Improve Flagship TinyMCE Button Style UX

### ISSUE THREAD

**Issue by m-e-h** [wpsitecare/flagship-library#7]
With the `'selector'` att it shows the button options grayed out and unavailable. It does work with them as `'block' => 'a'` but there isn't really an easy way to insert a url into them.

**Comment by robneu** [comment]
I think this is a limitation of the way the TinyMCE styleselect drop down works. In order for those styles to work as-is they have to be applied to an existing link. I'm not sure if there's a way to work around it other than using a different method to insert them.

I'll dig around a bit and see what I can come up with because it's not the greatest UX to have to insert a link and then a style.

**Comment by m-e-h** [comment]
Oh wow I see now.  I thought I tried that... It should be fine this way.
Actually kinda smart that it knows if it's a link or not. 

I've been messing around with [Shortcake](https://github.com/fusioneng/Shortcake) and it's awesome but a little overkill for buttons.

**Comment by robneu** [comment]
I was thinking it might be possible to do it with a custom trigger to the link insert modal. I'll think about it a bit more and see how involved it would be.

**Comment by m-e-h** [comment]
The link modal would be killer!
But if that's more work than it's worth, a tiny step up in UX may be to add the `a` selector inline and give it a default `href="#"`. The user should then just know they need to edit the url through the edit link button. 

I had a look at the tinymce page here http://www.tinymce.com/wiki.php/Configuration%3aformats
and see that there is an `attributes` parameter for the formats.
It's being used like this `attributes : {href : "#"},`
I just haven't been able to translate that into php...

Thoughts?

**Comment by robneu** [comment]
Ah, that seems like a nice middle ground. This is untested, but I think the setup would look like this:

```php
'title'      => __( 'Primary', 'flagship-library' ),
'inline'     => 'a',
'classes'    => 'button',
'attributes' => array(
	'href' => '#',
),
'exact'      => true,
```

**Comment by m-e-h** [comment]
Sweet. Thanks! This works. Not 100% sure this is better than the original method but we'll see.
Hoping to cut down on all the "click here" links scattered throughout my websites. :see_no_evil:

**Comment by robneu** [comment]
Awesome! I'm still going to give the link modal idea a spin. I'm just knee-deep in stuff for Compass and a few other projects at the moment. I'll leave this open for now to make sure I don't forgot.
